import { Country, InfoCategory } from './types';

export const COUNTRIES: Country[] = [
  // North America
  { id: 'usa', name: 'United States', flag: '🇺🇸', continent: 'North America', isEnglishSpeaking: true },
  { id: 'canada', name: 'Canada', flag: '🇨🇦', continent: 'North America', isEnglishSpeaking: true },
  { id: 'mexico', name: 'Mexico', flag: '🇲🇽', continent: 'North America' },
  { id: 'panama', name: 'Panama', flag: '🇵🇦', continent: 'North America' },
  { id: 'costa-rica', name: 'Costa Rica', flag: '🇨🇷', continent: 'North America' },
  { id: 'jamaica', name: 'Jamaica', flag: '🇯🇲', continent: 'North America', isEnglishSpeaking: true },
  { id: 'dominican-republic', name: 'Dominican Republic', flag: '🇩🇴', continent: 'North America' },
  { id: 'guatemala', name: 'Guatemala', flag: '🇬🇹', continent: 'North America' },
  { id: 'cuba', name: 'Cuba', flag: '🇨🇺', continent: 'North America' },
  { id: 'bahamas', name: 'Bahamas', flag: '🇧🇸', continent: 'North America', isEnglishSpeaking: true },
  { id: 'belize', name: 'Belize', flag: '🇧🇿', continent: 'North America', isEnglishSpeaking: true },
  { id: 'el-salvador', name: 'El Salvador', flag: '🇸🇻', continent: 'North America' },
  { id: 'honduras', name: 'Honduras', flag: '🇭🇳', continent: 'North America' },
  { id: 'nicaragua', name: 'Nicaragua', flag: '🇳🇮', continent: 'North America' },

  // Europe
  { id: 'uk', name: 'United Kingdom', flag: '🇬🇧', continent: 'Europe', isEnglishSpeaking: true },
  { id: 'germany', name: 'Germany', flag: '🇩🇪', continent: 'Europe' },
  { id: 'france', name: 'France', flag: '🇫🇷', continent: 'Europe' },
  { id: 'spain', name: 'Spain', flag: '🇪🇸', continent: 'Europe' },
  { id: 'italy', name: 'Italy', flag: '🇮🇹', continent: 'Europe' },
  { id: 'netherlands', name: 'Netherlands', flag: '🇳🇱', continent: 'Europe' },
  { id: 'portugal', name: 'Portugal', flag: '🇵🇹', continent: 'Europe' },
  { id: 'switzerland', name: 'Switzerland', flag: '🇨🇭', continent: 'Europe' },
  { id: 'sweden', name: 'Sweden', flag: '🇸🇪', continent: 'Europe' },
  { id: 'ireland', name: 'Ireland', flag: '🇮🇪', continent: 'Europe', isEnglishSpeaking: true },
  { id: 'poland', name: 'Poland', flag: '🇵🇱', continent: 'Europe' },
  { id: 'belgium', name: 'Belgium', flag: '🇧🇪', continent: 'Europe' },
  { id: 'austria', name: 'Austria', flag: '🇦🇹', continent: 'Europe' },
  { id: 'norway', name: 'Norway', flag: '🇳🇴', continent: 'Europe' },
  { id: 'denmark', name: 'Denmark', flag: '🇩🇰', continent: 'Europe' },
  { id: 'finland', name: 'Finland', flag: '🇫🇮', continent: 'Europe' },
  { id: 'greece', name: 'Greece', flag: '🇬🇷', continent: 'Europe' },
  { id: 'czech-republic', name: 'Czech Republic', flag: '🇨🇿', continent: 'Europe' },
  { id: 'hungary', name: 'Hungary', flag: '🇭🇺', continent: 'Europe' },
  { id: 'romania', name: 'Romania', flag: '🇷🇴', continent: 'Europe' },
  { id: 'turkey', name: 'Turkey', flag: '🇹🇷', continent: 'Europe' },
  { id: 'iceland', name: 'Iceland', flag: '🇮🇸', continent: 'Europe' },
  { id: 'luxembourg', name: 'Luxembourg', flag: '🇱🇺', continent: 'Europe' },
  { id: 'malta', name: 'Malta', flag: '🇲🇹', continent: 'Europe', isEnglishSpeaking: true },
  { id: 'cyprus', name: 'Cyprus', flag: '🇨🇾', continent: 'Europe', isEnglishSpeaking: true },
  { id: 'croatia', name: 'Croatia', flag: '🇭🇷', continent: 'Europe' },
  { id: 'bulgaria', name: 'Bulgaria', flag: '🇧🇬', continent: 'Europe' },
  { id: 'estonia', name: 'Estonia', flag: '🇪🇪', continent: 'Europe' },
  { id: 'latvia', name: 'Latvia', flag: '🇱🇻', continent: 'Europe' },
  { id: 'lithuania', name: 'Lithuania', flag: '🇱🇹', continent: 'Europe' },
  { id: 'slovakia', name: 'Slovakia', flag: '🇸🇰', continent: 'Europe' },
  { id: 'slovenia', name: 'Slovenia', flag: '🇸🇮', continent: 'Europe' },
  { id: 'albania', name: 'Albania', flag: '🇦🇱', continent: 'Europe' },
  { id: 'serbia', name: 'Serbia', flag: '🇷🇸', continent: 'Europe' },
  { id: 'monaco', name: 'Monaco', flag: '🇲🇨', continent: 'Europe' },

  // Asia
  { id: 'japan', name: 'Japan', flag: '🇯🇵', continent: 'Asia' },
  { id: 'south-korea', name: 'South Korea', flag: '🇰🇷', continent: 'Asia' },
  { id: 'china', name: 'China', flag: '🇨🇳', continent: 'Asia' },
  { id: 'singapore', name: 'Singapore', flag: '🇸🇬', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'thailand', name: 'Thailand', flag: '🇹🇭', continent: 'Asia' },
  { id: 'india', name: 'India', flag: '🇮🇳', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'vietnam', name: 'Vietnam', flag: '🇻🇳', continent: 'Asia' },
  { id: 'uae', name: 'United Arab Emirates', flag: '🇦🇪', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'malaysia', name: 'Malaysia', flag: '🇲🇾', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'indonesia', name: 'Indonesia', flag: '🇮🇩', continent: 'Asia' },
  { id: 'philippines', name: 'Philippines', flag: '🇵🇭', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'israel', name: 'Israel', flag: '🇮🇱', continent: 'Asia' },
  { id: 'saudi-arabia', name: 'Saudi Arabia', flag: '🇸🇦', continent: 'Asia' },
  { id: 'qatar', name: 'Qatar', flag: '🇶🇦', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'taiwan', name: 'Taiwan', flag: '🇹🇼', continent: 'Asia' },
  { id: 'pakistan', name: 'Pakistan', flag: '🇵🇰', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'bangladesh', name: 'Bangladesh', flag: '🇧🇩', continent: 'Asia' },
  { id: 'sri-lanka', name: 'Sri Lanka', flag: '🇱🇰', continent: 'Asia' },
  { id: 'kazakhstan', name: 'Kazakhstan', flag: '🇰🇿', continent: 'Asia' },
  { id: 'georgia', name: 'Georgia', flag: '🇬🇪', continent: 'Asia' },
  { id: 'armenia', name: 'Armenia', flag: '🇦🇲', continent: 'Asia' },
  { id: 'azerbaijan', name: 'Azerbaijan', flag: '🇦🇿', continent: 'Asia' },
  { id: 'kuwait', name: 'Kuwait', flag: '🇰🇼', continent: 'Asia' },
  { id: 'oman', name: 'Oman', flag: '🇴🇲', continent: 'Asia' },
  { id: 'bahrain', name: 'Bahrain', flag: '🇧🇭', continent: 'Asia', isEnglishSpeaking: true },
  { id: 'uzbekistan', name: 'Uzbekistan', flag: '🇺🇿', continent: 'Asia' },
  { id: 'nepal', name: 'Nepal', flag: '🇳🇵', continent: 'Asia' },
  { id: 'jordan', name: 'Jordan', flag: '🇯🇴', continent: 'Asia' },
  { id: 'lebanon', name: 'Lebanon', flag: '🇱🇧', continent: 'Asia' },

  // South America
  { id: 'brazil', name: 'Brazil', flag: '🇧🇷', continent: 'South America' },
  { id: 'argentina', name: 'Argentina', flag: '🇦🇷', continent: 'South America' },
  { id: 'chile', name: 'Chile', flag: '🇨🇱', continent: 'South America' },
  { id: 'colombia', name: 'Colombia', flag: '🇨🇴', continent: 'South America' },
  { id: 'peru', name: 'Peru', flag: '🇵🇪', continent: 'South America' },
  { id: 'ecuador', name: 'Ecuador', flag: '🇪🇨', continent: 'South America' },
  { id: 'uruguay', name: 'Uruguay', flag: '🇺🇾', continent: 'South America' },
  { id: 'paraguay', name: 'Paraguay', flag: '🇵🇾', continent: 'South America' },
  { id: 'bolivia', name: 'Bolivia', flag: '🇧🇴', continent: 'South America' },
  { id: 'guyana', name: 'Guyana', flag: '🇬🇾', continent: 'South America', isEnglishSpeaking: true },
  { id: 'suriname', name: 'Suriname', flag: '🇸🇷', continent: 'South America' },
  { id: 'venezuela', name: 'Venezuela', flag: '🇻🇪', continent: 'South America' },

  // Africa
  { id: 'south-africa', name: 'South Africa', flag: '🇿🇦', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'nigeria', name: 'Nigeria', flag: '🇳🇬', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'egypt', name: 'Egypt', flag: '🇪🇬', continent: 'Africa' },
  { id: 'kenya', name: 'Kenya', flag: '🇰🇪', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'morocco', name: 'Morocco', flag: '🇲🇦', continent: 'Africa' },
  { id: 'ghana', name: 'Ghana', flag: '🇬🇭', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'ethiopia', name: 'Ethiopia', flag: '🇪🇹', continent: 'Africa' },
  { id: 'tanzania', name: 'Tanzania', flag: '🇹🇿', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'mauritius', name: 'Mauritius', flag: '🇲🇺', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'seychelles', name: 'Seychelles', flag: '🇸🇨', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'tunisia', name: 'Tunisia', flag: '🇹🇳', continent: 'Africa' },
  { id: 'rwanda', name: 'Rwanda', flag: '🇷🇼', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'senegal', name: 'Senegal', flag: '🇸🇳', continent: 'Africa' },
  { id: 'uganda', name: 'Uganda', flag: '🇺🇬', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'algeria', name: 'Algeria', flag: '🇩🇿', continent: 'Africa' },
  { id: 'cameroon', name: 'Cameroon', flag: '🇨🇲', continent: 'Africa' },
  { id: 'ivory-coast', name: 'Ivory Coast', flag: '🇨🇮', continent: 'Africa' },
  { id: 'botswana', name: 'Botswana', flag: '🇧🇼', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'namibia', name: 'Namibia', flag: '🇳🇦', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'zambia', name: 'Zambia', flag: '🇿🇲', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'zimbabwe', name: 'Zimbabwe', flag: '🇿🇼', continent: 'Africa', isEnglishSpeaking: true },
  { id: 'madagascar', name: 'Madagascar', flag: '🇲🇬', continent: 'Africa' },

  // Oceania
  { id: 'australia', name: 'Australia', flag: '🇦🇺', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'nz', name: 'New Zealand', flag: '🇳🇿', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'fiji', name: 'Fiji', flag: '🇫🇯', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'png', name: 'Papua New Guinea', flag: '🇵🇬', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'vanuatu', name: 'Vanuatu', flag: '🇻🇺', continent: 'Oceania' },
  { id: 'samoa', name: 'Samoa', flag: '🇼🇸', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'tonga', name: 'Tonga', flag: '🇹🇴', continent: 'Oceania', isEnglishSpeaking: true },
  { id: 'solomon-islands', name: 'Solomon Islands', flag: '🇸🇧', continent: 'Oceania', isEnglishSpeaking: true },
];

export const CATEGORIES = [
  { type: InfoCategory.NEWS, icon: 'fa-newspaper', color: 'bg-orange-100 text-blue-600' },
  { type: InfoCategory.DAILY_LOCAL_NEWS, icon: 'fa-calendar-day', color: 'bg-orange-100 text-orange-600' },
  { type: InfoCategory.LOCAL_NEWS, icon: 'fa-location-dot', color: 'bg-red-100 text-red-600' },
  { type: InfoCategory.IMMIGRATION, icon: 'fa-passport', color: 'bg-purple-100 text-purple-600' },
  { type: InfoCategory.BENEFITS, icon: 'fa-hand-holding-heart', color: 'bg-green-100 text-green-600' },
  { type: InfoCategory.JOBS, icon: 'fa-briefcase', color: 'bg-orange-100 text-orange-600' },
  { type: InfoCategory.HOUSING, icon: 'fa-house', color: 'bg-cyan-100 text-cyan-600' },
  { type: InfoCategory.COMMUNITY, icon: 'fa-users', color: 'bg-pink-100 text-pink-600' },
];