name: Dev build

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
